Course batch status updater data product.
Sunbird-Ed/sunbird-data-products pull request #323
Opened 2021-01-18 14:29 UTC by manjudr

2021-01-19 07:38 UTC, PradyumnaNagendra requested changes

2021-01-19 07:38 UTC, PradyumnaNagendra commented on data-products/src/main/scala/org/sunbird/analytics/audit/CourseBatchStatusUpdaterJob.scala
> +    Option(enrolmentDate).map(x => x).getOrElse({
here endDate can also be null.
if enrolmentEndDate is not null -> return enrolmentEndDate
If (end Date is not null) && (enrolmentEndDate is null) -> set previous day of endDate as enrolmentEndDate.
if (endDate is null) && (enrolmentEndDate is null)  -> return null

2021-01-19 08:33 UTC, PradyumnaNagendra approved these changes

2021-02-15 09:50 UTC, manjudr commented
This feature is Implementing in 3.7.0 hence closing it.

2021-02-15 09:50 UTC, closed without merging