SB-2525 - Progress exhaust V2 Job Implementation
Sunbird-Ed/sunbird-data-products pull request #427
Opened 2021-07-14 12:43 UTC by manjudr

The progress exhaust V2 Job will fetch the best score from the user activity agg table instead of computing from the assessment agg table.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-29 09:32 UTC, maheshkumargangula approved these changes

2021-12-01 06:38 UTC, SanthoshVasabhaktula requested changes

2021-12-01 06:38 UTC, SanthoshVasabhaktula commented on data-products/src/main/scala/org/sunbird/analytics/exhaust/collection/BaseCollectionExhaustJob.scala
> +  }
Why are these progress exhaust specific functions in BaseCollectionExhaustJob?

2021-12-01 10:27 UTC, SanthoshVasabhaktula approved these changes

2021-12-01 12:05 UTC, merged