Test fixes added
Sunbird-Ed/sunbird-data-products pull request #524
Opened 2022-03-02 05:53 UTC by kumarks1122

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-02 10:01 UTC, anandp504 requested changes
Please implement the review comment changes.

2022-03-02 10:01 UTC, anandp504 commented on data-products/src/test/scala/org/sunbird/analytics/audit/TestScoreMetricMigrationJob.scala
> +    result.head.get(2).asInstanceOf[Seq[String]] should contain allElementsOf List("""{"max_score":10.0,"score":10.0,"type":"attempt_metrics","attempt_id":"attempat-001","content_id":"do_112876961957
Please deserialize to a case class and then perform the assertions. This won't work if the keys in the JSON string is in a different order. JSON is not an ordered list of key, value pairs.

2022-03-02 10:23 UTC, kumarks1122 commented on data-products/src/test/scala/org/sunbird/analytics/audit/TestScoreMetricMigrationJob.scala
> +    result.head.get(2).asInstanceOf[Seq[String]] should contain allElementsOf List("""{"max_score":10.0,"score":10.0,"type":"attempt_metrics","attempt_id":"attempat-001","content_id":"do_112876961957
@anandp504 : Sure

2022-03-03 05:13 UTC, anandp504 approved these changes
Approved :+1:

2022-03-03 05:13 UTC, merged