SB-29393 | Response exhaust job failure fixes for questionset added
Sunbird-Ed/sunbird-data-products pull request #543
Opened 2022-04-14 10:47 UTC by kumarks1122

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-18 10:41 UTC, reshmi-nair requested changes

2022-04-18 10:41 UTC, reshmi-nair commented on data-products/src/main/scala/org/sunbird/analytics/exhaust/collection/BaseCollectionExhaustJob.scala
> +    val questionresponse = RestUtil.post[CollectionDetails](apiURL, request).result.question
Pls change this to one call instead of 3 calls.

2022-04-19 05:36 UTC, reshmi-nair approved these changes

2022-04-20 10:00 UTC, manjudr approved these changes

2022-04-20 10:00 UTC, merged